package com.financial.services;

public enum BudgetType {
    GENERAL_BUDGET,
    REGULAR_BUDGET,
    PUBLIC_INVESTMENT_BUDGET,
    PUBLIC_INVESTMENT_NATIONAL_BUDGET,
    PUBLIC_INVESTMENT_COFUNDED_BUDGET,
}

